---
all:
  children:
    web:
      hosts:
        web-stg01:
          ansible_host: 10.0.2.10
          ansible_user: deploy
        web-stg02:
          ansible_host: 10.0.2.11
          ansible_user: deploy
    database:
      hosts:
        db-stg01:
          ansible_host: 10.0.2.20
          ansible_user: deploy
  vars:
    ansible_ssh_private_key_file: ~/.ssh/staging_key
