apiVersion: v1
kind: Secret
metadata:
  name: mariadb-db
  namespace: mariadb
  labels:
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/instance: mariadb
    app.kubernetes.io/component: database
type: Opaque
data:
  root-password: Y2hhbmdlbWU=
