Vagrant.configure("2") do |config|
  config.vm.box = "generic/bookworm"
  config.vm.box_check_update = false
  config.vm.hostname = "linux-learning"

  config.vm.provider :libvirt do |l|
    l.memory = 2048
    l.cpus = 1
    l.qemu_use_session = false
    l.driver = "kvm"
    l.cpu_mode = "host-model"
  end
end
