#!/bin/bash
# Generate SSH config from Vagrant for use with Ansible
# Usage: ./scripts/generate-ssh-config.sh [vm_count]
# Dependencies: vagrant, vagrant-libvirt

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
VM_COUNT="${1:-1}"
SSH_CONFIG_DIR="$SCRIPT_DIR/.vagrant"

mkdir -p "$SSH_CONFIG_DIR"

echo "# Vagrant SSH config - generated by generate-ssh-config.sh" > "$SSH_CONFIG_DIR/ssh-config"
echo "# Re-generate with: ./scripts/generate-ssh-config.sh" >> "$SSH_CONFIG_DIR/ssh-config"
echo "" >> "$SSH_CONFIG_DIR/ssh-config"

for i in $(seq 1 "$VM_COUNT"); do
    echo "Fetching SSH config for ansible-target-$i..."
    vagrant ssh-config "ansible-target-$i" >> "$SSH_CONFIG_DIR/ssh-config" 2>/dev/null || {
        echo "Warning: ansible-target-$i not running. Try: vagrant up ansible-target-$i"
    }
done

echo ""
echo "SSH config written to $SSH_CONFIG_DIR/ssh-config"
echo ""
echo "Test connection with:"
echo "  ansible all -i inventory/vagrant/hosts.yml -m ping"
