---
ansible_user: vagrant
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_common_args: '-F .vagrant/ssh-config'

env: vagrant
timezone: UTC

ntp_servers:
  - 0.pool.ntp.org

# Apache
apache_listen_port: 80
apache_servername: "{{ inventory_hostname }}"
apache_document_root: /var/www/html

# Packages
base_packages:
  - vim
  - htop
  - curl
  - wget
  - git
  - tmux
  - tree
