apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "messageboard.fullname" . }}-db
  labels:
    app.kubernetes.io/component: {{ include "messageboard.fullname" . }}-db
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: {{ include "messageboard.fullname" . }}-db
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{- include "messageboard.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 3306
