{{- if and .Values.mariadb.enabled (not .Values.mariadb.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "messageboard.fullname" . }}-db
  labels:
    {{- include "messageboard.labels" . | nindent 4 }}
type: Opaque
data:
  mariadb-root-password: {{ .Values.mariadb.rootPassword | default "changeme" | b64enc | quote }}
  database-name: {{ .Values.mariadb.database | default "app" | b64enc | quote }}
  database-user: {{ .Values.mariadb.user | default "app" | b64enc | quote }}
  database-password: {{ .Values.mariadb.password | default "apppass" | b64enc | quote }}
{{- end }}
