apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messageboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_ME
    targetRevision: HEAD
    path: kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: messageboard
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
